### ISSUE TITLE
change methods structure for select

### ISSUE THREAD

**Issue by fatfattony** [Mushroom-man/DataBaseConnector#5]
Change request generation. We need to enter parameters in any order, for example
select('User', 'u')->where('u.name = 'vasya')->andWhere('u.second_name = petrovich')->orderBy('u.last_name', 'DESC')->andWhere('u.last_name = pupkin')->getResult();

so you should add where, order, group conditions to array and then generate full request from them. 
Note that we need only andWhere now, not orWhere. and we should point conditions in any order we want. 
Here is only one rule:
select must be first, get result must be last.

**Comment by Mushroom-man** [comment]
Do I understand the task correctly? Select must be first, get result last. And the fact that between them should fall into the array and sorted in the right order to perform. Even if parameters are entered in any order

**Comment by fatfattony** [comment]
yep

**Comment by fatfattony** [comment]
you can use only andWhere method which add some condition to array and don't use where(it do the same but only for the first time). You can use where method but it must call andWhere method inside.
